server:
  port: 8881

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/

spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        serviceId: config-server


